<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Chewy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amita&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css"/>
    <link rel="stylesheet" href="css/main.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title>Tache</title>
</head>
<body>
<main class="flex">
    <section class="flex">
        <article>
            <form class="supp" action="controller/supp.php" method="POST">
                <ul>
                    <?=$tache=post_tache();?>
                </ul>
                <div class="buttons"><input type="submit" class="btn-hover color-8" name="supprimer" value="SUPPRIMER"></div>
            </form>
        </article>
    </section>

    <section class="form flex">
        <form class="add" action="controller/controller.php" method="POST">
            <fieldset>
                <legend>Tâche</legend>
                <label for="titre">Titre :</label>
                <input type="text" id="titre" name="titre" required="required" placeholder="Titre de la tâche">
                <label for="description">Déscription de la tâche :</label>
                <textarea id="description" name="description" rows="5" cols="33"
                          placeholder="Détail de la tâche"></textarea>
                <label for="date">Date de fin :</label>
                <input type="date" name="date">
                <label for="level">Priorité :</label>
                <div class="flex">
                    <div class="element">
                        <input type="radio" id="bouton_1" name="level" value="basse">
                        <label for="bouton_1">Basse</label>
                    </div>
                    <div class="element">
                        <input type="radio" id="bouton_2" name="level" value="normal">
                        <label for="bouton_2">Normal</label>
                    </div>
                    <div class="element">
                        <input type="radio" id="bouton_3" name="level" value="haute">
                        <label for="bouton_3">Haute</label>
                    </div>
                </div>
                <input type="submit" name="enregistrer" value="Enregistrer">
            </fieldset>
        </form>
    </section>
</main>
<footer>
</footer>
</body>
</html>
